language: ruby
rvm:
- 2.5.1
addons:
  ssh_known_hosts: 207.246.83.219
before_deploy:
- openssl aes-256-cbc -K $encrypted_d5d623f71726_key -iv $encrypted_d5d623f71726_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_rsa
- ssh-add .travis/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script:
      rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@207.246.83.219:~/production;
      ssh root@207.246.83.219 systemctl restart production.service;
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@207.246.83.219:~/staging;
      ssh root@207.246.83.219 systemctl restart staging.service;
    on:
      branch: staging
